# Generated by Django 3.0.3 on 2020-06-28 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clust40PG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clust40pg', models.CharField(max_length=264, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operon_ID', models.CharField(max_length=264, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genome_ID_x', models.CharField(max_length=264, unique=True)),
                ('phylum', models.CharField(max_length=264)),
                ('species', models.CharField(max_length=264)),
                ('genus', models.CharField(max_length=264)),
                ('strain', models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='EcisDataBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scaffold', models.CharField(max_length=264)),
                ('gene_id', models.CharField(max_length=264, unique=True)),
                ('locus_tag_x', models.CharField(max_length=264)),
                ('start_coord_x', models.CharField(max_length=264)),
                ('end_coord_x', models.CharField(max_length=264)),
                ('core_whole', models.CharField(max_length=264)),
                ('len_aa', models.CharField(max_length=264)),
                ('clust40pg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecis_web_first_app.Clust40PG')),
                ('genome_ID_x', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecis_web_first_app.Species')),
                ('operon_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecis_web_first_app.Operons')),
            ],
        ),
    ]
