# Generated by Django 3.0.3 on 2020-09-21 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ecis_web_first_app', '0044_auto_20200922_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clust40PG',
            fields=[
                ('clust40pg', models.CharField(max_length=264, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EcisDataBase',
            fields=[
                ('scaffold', models.CharField(max_length=264)),
                ('gene_id', models.CharField(max_length=264, primary_key=True, serialize=False, unique=True)),
                ('locus_tag_x', models.CharField(max_length=264)),
                ('start_coord_x', models.IntegerField()),
                ('end_coord_x', models.IntegerField()),
                ('core_whole', models.CharField(max_length=264)),
                ('len_aa', models.IntegerField()),
                ('pfams_list', models.CharField(max_length=264)),
                ('clust40pg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecis_web_first_app.Clust40PG')),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('genome_ID_x', models.CharField(max_length=264, primary_key=True, serialize=False, unique=True)),
                ('domain', models.CharField(max_length=264)),
                ('phylum', models.CharField(max_length=264)),
                ('class_id', models.CharField(max_length=264)),
                ('order', models.CharField(max_length=264)),
                ('family', models.CharField(max_length=264)),
                ('species', models.CharField(max_length=264)),
                ('genus', models.CharField(max_length=264)),
                ('strain', models.CharField(max_length=264)),
                ('ecosystem', models.CharField(max_length=264)),
                ('ecosystem_cat', models.CharField(max_length=264)),
                ('ecosystem_subtype', models.CharField(max_length=264)),
                ('ecosystem_type', models.CharField(max_length=264)),
                ('gram_staining', models.CharField(max_length=264)),
                ('habitat', models.CharField(max_length=264)),
                ('host_name', models.CharField(max_length=264)),
                ('isolation', models.CharField(max_length=264)),
                ('metabolism', models.CharField(max_length=264)),
                ('motility', models.CharField(max_length=264)),
                ('temp_range', models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='PfamDb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pfam_id', models.CharField(max_length=264)),
                ('pfam_name', models.CharField(max_length=264)),
                ('pfam_length', models.CharField(max_length=264)),
                ('pfam_query_start', models.IntegerField()),
                ('pfam_query_end', models.IntegerField()),
                ('pfam_evalue', models.CharField(max_length=264)),
                ('gene_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecis_web_first_app.EcisDataBase')),
                ('genome_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecis_web_first_app.Species')),
            ],
        ),
        migrations.CreateModel(
            name='Operons',
            fields=[
                ('operon_ID', models.CharField(max_length=264, primary_key=True, serialize=False, unique=True)),
                ('index_ID', models.IntegerField()),
                ('operon_IM', models.ImageField(upload_to='static/ecis_web_first_app/uploaded_img')),
                ('genus', models.CharField(max_length=264)),
                ('species', models.CharField(max_length=264)),
                ('strain', models.CharField(max_length=264)),
                ('genome_ID_x', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecis_web_first_app.Species')),
            ],
        ),
        migrations.AddField(
            model_name='ecisdatabase',
            name='genome_ID_x',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecis_web_first_app.Species'),
        ),
        migrations.AddField(
            model_name='ecisdatabase',
            name='operon_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecis_web_first_app.Operons'),
        ),
    ]
